# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20170423_1342'),
        ('Blog', '0006_auto_20170423_1621'),
    ]

    operations = [
    ]
